# Think Stats Exercise 4.2
# The numbers generated by numpy.random.random are supposed to be uniform between
# 0 and 1; that is, every value in the range should have the same probability.
# Generate 1000 numbers from numpy.random.random and plot their PMF. What goes wrong?
# Now plot the CDF. Is the distribution uniform?


import numpy as np
import thinkstats2
import thinkplot

# Generate 1000 randome numebrs and define PMF.
random = np.random.random(1000)
pmf = thinkstats2.Pmf(random, label='random')

# Plot and save PMF chart.
thinkplot.Pmf(pmf, linewidth = .05)
thinkplot.Config(xlabel='Random Number', ylabel='PMF')
thinkplot.Save(root='PMF_Random')

# Define, plot, and save CDF for comparison.
cdf = thinkstats2.Cdf(random, label='random')
thinkplot.Cdf(cdf)
thinkplot.Config(xlabel='Random Number', ylabel='CDF')
thinkplot.Save(root='CDF_Random')
